name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install sbt
      run: sudo apt install sbt
    - name: run sbt test
      run: sbt test
